###
POST http://localhost:4000/api/register/
content-type: application/json

{
    "username": "Me1",
    "password": "password123"
}

###
POST http://localhost:4000/api/login/
content-type: application/json

{
    "username": "Me1",
    "password": "password123"
}

###
GET http://localhost:4000/api/users
content-type: application/json